name = "LoVe"
defaultTargets = ["LoVe"]

[leanOptions]
autoImplicit = false
linter.unusedVariables = false 
# linter.unusedTactic = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "a719ba5c3115d47b68bf0497a9dd1bcbb21ea663"

[[require]]
name = "autograder" 
git = "https://github.com/robertylewis/lean4-autograder-main" 
rev = "8ab518f40e807d514b8de6a09b68a84559a0dda0"


[[lean_lib]]
name = "LoVe"
